<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Data Transformation 3: Finetuned Data Manipulation | Introduction to R</title>
  <meta name="description" content="This is the course handbook for the Glasgow University Open Studies course Introduction to R, academic session 2019-2020." />
  <meta name="generator" content="bookdown 0.15 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Data Transformation 3: Finetuned Data Manipulation | Introduction to R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the course handbook for the Glasgow University Open Studies course Introduction to R, academic session 2019-2020." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Data Transformation 3: Finetuned Data Manipulation | Introduction to R" />
  
  <meta name="twitter:description" content="This is the course handbook for the Glasgow University Open Studies course Introduction to R, academic session 2019-2020." />
  

<meta name="author" content="Gaby Mahrholz, Rebecca J. Lai, Kate Haining, Greta Todorova, and Wilhelmiina Toivo" />


<meta name="date" content="2020-01-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-transformation-2-two-table-verbs.html"/>
<link rel="next" href="recap-1.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#intended-learning-outcomes"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-will-i-need-to-complete-this-course"><i class="fa fa-check"></i>What will I need to complete this course?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-assessments"><i class="fa fa-check"></i>About the Assessments</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#formative-assessments"><i class="fa fa-check"></i>Formative Assessments</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#summative-assessments"><i class="fa fa-check"></i>Summative Assessments</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-submit-your-assessments"><i class="fa fa-check"></i>How to Submit Your Assessments</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assistance"><i class="fa fa-check"></i>Assistance</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-are-these-materials-open"><i class="fa fa-check"></i>Why are these materials open?</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#intended-learning-outcomes-1"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#computer-literacy-basics"><i class="fa fa-check"></i><b>1.1</b> Computer Literacy Basics</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#r-and-r-studio"><i class="fa fa-check"></i><b>1.2</b> R and R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="introduction.html"><a href="introduction.html#r"><i class="fa fa-check"></i><b>1.2.1</b> R</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction.html"><a href="introduction.html#rstudio-ide"><i class="fa fa-check"></i><b>1.2.2</b> RStudio IDE</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#r-r-studio-and-associated-file-types"><i class="fa fa-check"></i><b>1.3</b> R, R Studio and Associated File Types</a><ul>
<li class="chapter" data-level="1.3.1" data-path="introduction.html"><a href="introduction.html#file-structuredirectories"><i class="fa fa-check"></i><b>1.3.1</b> File Structure/Directories</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction.html"><a href="introduction.html#file-extensions"><i class="fa fa-check"></i><b>1.3.2</b> File Extensions</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction.html"><a href="introduction.html#zip-files"><i class="fa fa-check"></i><b>1.3.3</b> .zip Files</a></li>
<li class="chapter" data-level="1.3.4" data-path="introduction.html"><a href="introduction.html#rstudio-specific-files"><i class="fa fa-check"></i><b>1.3.4</b> RStudio Specific Files</a></li>
<li class="chapter" data-level="1.3.5" data-path="introduction.html"><a href="introduction.html#r-files"><i class="fa fa-check"></i><b>1.3.5</b> .r Files</a></li>
<li class="chapter" data-level="1.3.6" data-path="introduction.html"><a href="introduction.html#rmd-files"><i class="fa fa-check"></i><b>1.3.6</b> .Rmd files</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#comments"><i class="fa fa-check"></i><b>1.4</b> Comments</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#saving-your-file"><i class="fa fa-check"></i><b>1.5</b> Saving your file</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#sessions"><i class="fa fa-check"></i><b>1.6</b> Sessions</a><ul>
<li class="chapter" data-level="1.6.1" data-path="introduction.html"><a href="introduction.html#what-is-a-session-in-r"><i class="fa fa-check"></i><b>1.6.1</b> What is a session in R?</a></li>
<li class="chapter" data-level="1.6.2" data-path="introduction.html"><a href="introduction.html#restarting-your-current-session"><i class="fa fa-check"></i><b>1.6.2</b> Restarting Your Current Session</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#packages"><i class="fa fa-check"></i><b>1.7</b> Packages</a><ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#installing-packages"><i class="fa fa-check"></i><b>1.7.1</b> Installing Packages</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction.html"><a href="introduction.html#load-tidyverse"><i class="fa fa-check"></i><b>1.7.2</b> Loading Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#functions"><i class="fa fa-check"></i><b>1.8</b> Functions</a><ul>
<li class="chapter" data-level="1.8.1" data-path="introduction.html"><a href="introduction.html#what-is-a-function"><i class="fa fa-check"></i><b>1.8.1</b> What is a function?</a></li>
<li class="chapter" data-level="1.8.2" data-path="introduction.html"><a href="introduction.html#the-anatomy-of-a-function-names-and-arguments"><i class="fa fa-check"></i><b>1.8.2</b> The Anatomy of a Function: names and arguments</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#formative-assignment"><i class="fa fa-check"></i><b>1.9</b> Formative Assignment</a><ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#accessing"><i class="fa fa-check"></i><b>1.9.1</b> Access to RStudio</a></li>
<li class="chapter" data-level="1.9.2" data-path="introduction.html"><a href="introduction.html#maximising-reproducibility-and-visibility"><i class="fa fa-check"></i><b>1.9.2</b> Maximising Reproducibility and Visibility</a></li>
<li class="chapter" data-level="1.9.3" data-path="introduction.html"><a href="introduction.html#installing-and-loading-tidyverse"><i class="fa fa-check"></i><b>1.9.3</b> Installing and Loading Tidyverse</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-data.html"><a href="introduction-to-data.html"><i class="fa fa-check"></i><b>2</b> Introduction to Data</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-data.html"><a href="introduction-to-data.html#intended-learning-outcomes-2"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
<li class="chapter" data-level="2.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#pre-steps"><i class="fa fa-check"></i><b>2.1</b> Pre-Steps</a><ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#downloading-materials"><i class="fa fa-check"></i><b>2.1.1</b> Downloading materials</a></li>
<li class="chapter" data-level="2.1.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#unzipping-the-zip-folder"><i class="fa fa-check"></i><b>2.1.2</b> Unzipping the zip folder</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#setting-the-working-directory"><i class="fa fa-check"></i><b>2.1.3</b> Setting the working directory</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction-to-data.html"><a href="introduction-to-data.html#load-tidyverse-into-the-library"><i class="fa fa-check"></i><b>2.1.4</b> Load tidyverse into the library</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#basic-data-types"><i class="fa fa-check"></i><b>2.2</b> Basic data types</a><ul>
<li class="chapter" data-level="2.2.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#character"><i class="fa fa-check"></i><b>2.2.1</b> Character</a></li>
<li class="chapter" data-level="2.2.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#numeric"><i class="fa fa-check"></i><b>2.2.2</b> Numeric</a></li>
<li class="chapter" data-level="2.2.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#logical"><i class="fa fa-check"></i><b>2.2.3</b> Logical</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#vectors"><i class="fa fa-check"></i><b>2.3</b> Vectors</a><ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#creating-vectors"><i class="fa fa-check"></i><b>2.3.1</b> Creating vectors</a></li>
<li class="chapter" data-level="2.3.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#converting-vectors-into-different-data-types-of-vectors-aka-funky-things-we-can-do"><i class="fa fa-check"></i><b>2.3.2</b> Converting vectors into different data types of vectors aka funky things we can do</a></li>
<li class="chapter" data-level="2.3.3" data-path="introduction-to-data.html"><a href="introduction-to-data.html#adding-elements-to-existing-vectors"><i class="fa fa-check"></i><b>2.3.3</b> Adding elements to existing vectors</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-data.html"><a href="introduction-to-data.html#tibble---the-new-way-of-creating-a-dataframe"><i class="fa fa-check"></i><b>2.4</b> Tibble - the new way of creating a dataframe</a><ul>
<li class="chapter" data-level="2.4.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#what-the-heck-is-a-tibble-do-you-mean-table"><i class="fa fa-check"></i><b>2.4.1</b> What the heck is a tibble? Do you mean table?</a></li>
<li class="chapter" data-level="2.4.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#how-to-make-a-tibble-from-scratch"><i class="fa fa-check"></i><b>2.4.2</b> How to make a tibble from scratch</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-data.html"><a href="introduction-to-data.html#reading-in-data"><i class="fa fa-check"></i><b>2.5</b> Reading in data</a><ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-to-data.html"><a href="introduction-to-data.html#from-pre-existing-databases"><i class="fa fa-check"></i><b>2.5.1</b> from pre-existing databases</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-to-data.html"><a href="introduction-to-data.html#from-existing-data-files"><i class="fa fa-check"></i><b>2.5.2</b> from existing data files</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="introduction-to-data.html"><a href="introduction-to-data.html#last-point-for-today"><i class="fa fa-check"></i><b>2.6</b> Last point for today</a></li>
<li class="chapter" data-level="2.7" data-path="introduction-to-data.html"><a href="introduction-to-data.html#summative-homework"><i class="fa fa-check"></i><b>2.7</b> Summative Homework</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html"><i class="fa fa-check"></i><b>3</b> Data Transformation 1: Basic One Table Verbs</a><ul>
<li class="chapter" data-level="" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#intended-learning-outcomes-3"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
<li class="chapter" data-level="3.1" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#data-wrangling"><i class="fa fa-check"></i><b>3.1</b> Data Wrangling</a></li>
<li class="chapter" data-level="3.2" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#pre-steps-1"><i class="fa fa-check"></i><b>3.2</b> Pre-Steps</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#downloading-materials-1"><i class="fa fa-check"></i><b>3.2.1</b> Downloading materials</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#unzipping-the-zip-folder-1"><i class="fa fa-check"></i><b>3.2.2</b> Unzipping the zip folder</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#setting-the-working-directory-1"><i class="fa fa-check"></i><b>3.2.3</b> Setting the working directory</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#load-tidyverse-into-the-library-1"><i class="fa fa-check"></i><b>3.2.4</b> Load tidyverse into the library</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#reading-in-the-data"><i class="fa fa-check"></i><b>3.2.5</b> Reading in the data</a></li>
<li class="chapter" data-level="3.2.6" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#view-the-data"><i class="fa fa-check"></i><b>3.2.6</b> View the data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#select"><i class="fa fa-check"></i><b>3.3</b> select()</a></li>
<li class="chapter" data-level="3.4" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#arrange"><i class="fa fa-check"></i><b>3.4</b> arrange()</a></li>
<li class="chapter" data-level="3.5" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#filter"><i class="fa fa-check"></i><b>3.5</b> filter()</a><ul>
<li class="chapter" data-level="3.5.1" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#single-criterion"><i class="fa fa-check"></i><b>3.5.1</b> Single criterion</a></li>
<li class="chapter" data-level="3.5.2" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#multiple-criteria"><i class="fa fa-check"></i><b>3.5.2</b> Multiple criteria</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#mutate"><i class="fa fa-check"></i><b>3.6</b> mutate()</a></li>
<li class="chapter" data-level="3.7" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#formative-homework"><i class="fa fa-check"></i><b>3.7</b> Formative Homework</a><ul>
<li class="chapter" data-level="3.7.1" data-path="data-transformation-1-basic-one-table-verbs.html"><a href="data-transformation-1-basic-one-table-verbs.html#brief-introduction-to-the-homework-data"><i class="fa fa-check"></i><b>3.7.1</b> Brief introduction to the homework data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html"><i class="fa fa-check"></i><b>4</b> Data Transformation 2: Two Table Verbs</a><ul>
<li class="chapter" data-level="" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#intended-learning-outcomes-4"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
<li class="chapter" data-level="4.1" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#pre-steps-2"><i class="fa fa-check"></i><b>4.1</b> Pre-Steps</a></li>
<li class="chapter" data-level="4.2" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#group_by-and-summarise"><i class="fa fa-check"></i><b>4.2</b> group_by() and summarise()</a></li>
<li class="chapter" data-level="4.3" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#the-pipe-operator"><i class="fa fa-check"></i><b>4.3</b> The pipe operator (%&gt;%)</a></li>
<li class="chapter" data-level="4.4" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#two-table-verbs"><i class="fa fa-check"></i><b>4.4</b> Two-Table Verbs</a><ul>
<li class="chapter" data-level="4.4.1" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#mutating-join-verbs"><i class="fa fa-check"></i><b>4.4.1</b> Mutating Join Verbs</a></li>
<li class="chapter" data-level="4.4.2" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#binding-join-verbs"><i class="fa fa-check"></i><b>4.4.2</b> Binding Join Verbs</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#additional-information"><i class="fa fa-check"></i><b>4.5</b> Additional information</a></li>
<li class="chapter" data-level="4.6" data-path="data-transformation-2-two-table-verbs.html"><a href="data-transformation-2-two-table-verbs.html#summative-homework-1"><i class="fa fa-check"></i><b>4.6</b> Summative Homework</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html"><i class="fa fa-check"></i><b>5</b> Data Transformation 3: Finetuned Data Manipulation</a><ul>
<li class="chapter" data-level="" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#intended-learning-outcomes-5"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
<li class="chapter" data-level="5.1" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#pre-steps-3"><i class="fa fa-check"></i><b>5.1</b> Pre-steps</a></li>
<li class="chapter" data-level="5.2" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#gather-and-spread"><i class="fa fa-check"></i><b>5.2</b> gather() and spread()</a><ul>
<li class="chapter" data-level="5.2.1" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#gather"><i class="fa fa-check"></i><b>5.2.1</b> gather()</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#spread"><i class="fa fa-check"></i><b>5.2.2</b> spread()</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#unite-and-separate"><i class="fa fa-check"></i><b>5.3</b> unite() and separate()</a></li>
<li class="chapter" data-level="5.4" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#rename"><i class="fa fa-check"></i><b>5.4</b> rename()</a></li>
<li class="chapter" data-level="5.5" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#recode"><i class="fa fa-check"></i><b>5.5</b> recode()</a></li>
<li class="chapter" data-level="5.6" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#ifelse-and-case_when"><i class="fa fa-check"></i><b>5.6</b> ifelse and case_when</a></li>
<li class="chapter" data-level="5.7" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#distinct"><i class="fa fa-check"></i><b>5.7</b> distinct</a></li>
<li class="chapter" data-level="5.8" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#additional-information-1"><i class="fa fa-check"></i><b>5.8</b> Additional information</a></li>
<li class="chapter" data-level="5.9" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#bonus-mutate-rownames-from-the-mtcars"><i class="fa fa-check"></i><b>5.9</b> Bonus: mutate rownames from the mtcars</a></li>
<li class="chapter" data-level="5.10" data-path="data-transformation-3-finetuned-data-manipulation.html"><a href="data-transformation-3-finetuned-data-manipulation.html#formative-homework-1"><i class="fa fa-check"></i><b>5.10</b> Formative Homework</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="recap-1.html"><a href="recap-1.html"><i class="fa fa-check"></i><b>6</b> Recap 1</a><ul>
<li class="chapter" data-level="6.1" data-path="recap-1.html"><a href="recap-1.html#outline-for-today"><i class="fa fa-check"></i><b>6.1</b> Outline for today</a></li>
<li class="chapter" data-level="6.2" data-path="recap-1.html"><a href="recap-1.html#in-class-practice-exam"><i class="fa fa-check"></i><b>6.2</b> In-class practice exam</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html"><i class="fa fa-check"></i><b>7</b> Data Visualisation 1</a><ul>
<li class="chapter" data-level="" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#intended-learning-outcomes-6"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html"><i class="fa fa-check"></i><b>8</b> Data Visualisation 2</a><ul>
<li class="chapter" data-level="" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#intended-learning-outcomes-7"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="errors.html"><a href="errors.html"><i class="fa fa-check"></i><b>9</b> Errors</a><ul>
<li class="chapter" data-level="9.1" data-path="errors.html"><a href="errors.html#under-construction"><i class="fa fa-check"></i><b>9.1</b> Under Construction</a></li>
<li class="chapter" data-level="" data-path="errors.html"><a href="errors.html#intended-learning-outcomes-8"><i class="fa fa-check"></i>Intended Learning Outcomes</a></li>
<li class="chapter" data-level="9.2" data-path="errors.html"><a href="errors.html#errors-how-to-avoid-some-and-live-through-the-rest"><i class="fa fa-check"></i><b>9.2</b> Errors: How to avoid some and live through the rest</a><ul>
<li class="chapter" data-level="9.2.1" data-path="errors.html"><a href="errors.html#debugging"><i class="fa fa-check"></i><b>9.2.1</b> Debugging</a></li>
<li class="chapter" data-level="9.2.2" data-path="errors.html"><a href="errors.html#debugging-questions"><i class="fa fa-check"></i><b>9.2.2</b> Debugging Questions</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="errors.html"><a href="errors.html#seeking-help"><i class="fa fa-check"></i><b>9.3</b> Seeking Help</a><ul>
<li class="chapter" data-level="9.3.1" data-path="errors.html"><a href="errors.html#searching-for-help-online"><i class="fa fa-check"></i><b>9.3.1</b> Searching for Help Online</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="errors.html"><a href="errors.html#custom-functions"><i class="fa fa-check"></i><b>9.4</b> Custom Functions</a></li>
<li class="chapter" data-level="9.5" data-path="errors.html"><a href="errors.html#living-through-errors-how-reproducible-code-enables-science-to-self-correct"><i class="fa fa-check"></i><b>9.5</b> Living Through Errors: How reproducible code enables science to self-correct</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="recap-2-before-the-final-assessment.html"><a href="recap-2-before-the-final-assessment.html"><i class="fa fa-check"></i><b>10</b> Recap 2: Before the Final Assessment</a><ul>
<li class="chapter" data-level="10.1" data-path="recap-2-before-the-final-assessment.html"><a href="recap-2-before-the-final-assessment.html#intended-learning-outcomes-9"><i class="fa fa-check"></i><b>10.1</b> Intended Learning Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html"><i class="fa fa-check"></i>Appendices</a><ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#changing-the-appearance-of-rmarkdown"><i class="fa fa-check"></i>Changing the Appearance of RMarkdown</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#source-materials"><i class="fa fa-check"></i>Source Materials</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#further-reading"><i class="fa fa-check"></i>Further Reading</a><ul>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#statistics"><i class="fa fa-check"></i>Statistics</a></li>
<li class="chapter" data-level="" data-path="appendices.html"><a href="appendices.html#more-advanced-use-of-r"><i class="fa fa-check"></i>More Advanced Use of R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>11</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-transformation-3-finetuned-data-manipulation" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Data Transformation 3: Finetuned Data Manipulation</h1>
<div id="intended-learning-outcomes-5" class="section level2 unnumbered">
<h2>Intended Learning Outcomes</h2>
<p>The whole purpose of this lecture is to tidy up dataframe and expose you to a bunch of useful functions that would make your daily life easier when dealing with your own data. By the end of today, you will know</p>
<ol style="list-style-type: decimal">
<li>How to rearrange data from long format into to wide format and vice versa</li>
<li>How to combine and separate columns</li>
<li>How to rename column headers</li>
<li>How to recode cell values</li>
<li>How to mutate based on conditions</li>
<li>How to obtain unique values from your data</li>
</ol>
</div>
<div id="pre-steps-3" class="section level2">
<h2><span class="header-section-number">5.1</span> Pre-steps</h2>
<p>Before we can start to focus on some other functions that might come in handy for data manipulation, we need to make sure to load <code>tidyverse</code> into the library and read the data we will be working with today into our <code>Global Environment</code>.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb213-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb213-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb213-2"></a>data_SMH &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;Student_Mental_Health.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="gather-and-spread" class="section level2">
<h2><span class="header-section-number">5.2</span> gather() and spread()</h2>
<p><code>gather()</code> and <code>spread()</code> are part of <code>tidyr</code> (also part of the tidyverse package) and help you to rearrange the shape of your data. To get your data into long format, you would use <code>gather()</code>; if you wanted to get your data from long to wide format, you would need <code>spread()</code>. Here is a nice gif animation by Garrick Aden-Buie () that shows you how <code>gather()</code> and <code>spread()</code> work.</p>
<center>
<img src="images/tidyr-spread-gather.gif" >
</center>
<p>The catch is that you need to know what kind of statistics you want to run, and how your data needs to be structured in order for you to achieve that. We cannot tell you that in this mere 10 week introduction course, however, we can give you the tools to prepare you as best as we can for what’s out there.</p>
<div id="gather" class="section level3">
<h3><span class="header-section-number">5.2.1</span> gather()</h3>
<p>We can start this lecture by looking at a practical example in the build-in dataset <code>table1</code> to <code>table5</code>. They show the number of Tuberculosis cases documented by the World Health Organization in Afghanistan, Brazil, and China between 1999 and 2000 (the full dataset is called <code>who</code>). The data is part of the <code>tidyverse</code> package, so as long as we have <code>tidyverse</code> loaded into the library, there should not be an issue in accessing this dataset.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb214-1"></a>table1</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country      year  cases population
##   &lt;chr&gt;       &lt;int&gt;  &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan  1999    745   19987071
## 2 Afghanistan  2000   2666   20595360
## 3 Brazil       1999  37737  172006362
## 4 Brazil       2000  80488  174504898
## 5 China        1999 212258 1272915272
## 6 China        2000 213766 1280428583</code></pre>
<p><code>table1</code> has a very tidy structure. You can see the data contains values associated with four variables (<code>country</code>, <code>year</code>, <code>cases</code>, and <code>population</code>). <code>table4a</code> however, looks a touch not right.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb216-1"></a>table4a</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   country     `1999` `2000`
## * &lt;chr&gt;        &lt;int&gt;  &lt;int&gt;
## 1 Afghanistan    745   2666
## 2 Brazil       37737  80488
## 3 China       212258 213766</code></pre>
<p>Somehow the values for the columns <code>year</code> and <code>cases</code> are missing and instead we find two separate columns for <code>1999</code> and <code>2000</code> that have all <code>cases</code> values listed. This is a problem as <code>1999</code> and <code>2000</code> are actual values and not variables.</p>
<p>Currently the data is in what is called a <code>wide format</code>. The function <code>gather()</code> comes in handy when we want to get the data back into the shape of a <code>long format</code> like in <code>table1</code>. <code>gather()</code> is structured like:</p>
<p><br></p>
<center>
<img src="images/gather.PNG" >
</center>
<p><br></p>
<p>Let’s apply this formula to <code>table4a</code></p>
<ul>
<li>We need a dataframe that we want to modify -&gt; <code>table4a</code></li>
<li>We need to come up with the name of a new column in which the values of 1999 and 2000 will be stored -&gt; <code>year</code></li>
<li>We need to come up with the name of a new column in which all the case values will be stored -&gt; <code>cases</code></li>
<li>And finally, we need to tell R which columns in <code>table4a</code> we want to turn into long format (i.e. the columns of the 7 subscales) -&gt; 1999 and 2000 (Note that “1999” and “2000” are non-syntactic names as they don’t start with a letter. The solution is to surround them in backticks.)</li>
</ul>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb218-1"></a><span class="kw">gather</span>(table4a, <span class="dt">key =</span> year, <span class="dt">value =</span> cases, <span class="st">`</span><span class="dt">1999</span><span class="st">`</span><span class="op">:</span><span class="st">`</span><span class="dt">2000</span><span class="st">`</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   country     year   cases
##   &lt;chr&gt;       &lt;chr&gt;  &lt;int&gt;
## 1 Afghanistan 1999     745
## 2 Brazil      1999   37737
## 3 China       1999  212258
## 4 Afghanistan 2000    2666
## 5 Brazil      2000   80488
## 6 China       2000  213766</code></pre>
<div class="funfact">
<p>
Here we have only 2 columns to reshape <code>1999</code> and <code>2000</code>. We could have written <code>gather(table4a, year, cases, `1999`, `2000`)</code>.
</p>
</div>
<div class="task">
<p>
<strong>Your turn</strong>
</p>
<p>
Use the <code>gather()</code> function with the student mental health data <code>data_SMH</code> to reshape it from wide format into long format.
</p>
<p>
Step 1: Only work with a selection of columns from <code>data_SMH</code> to see better what is going on. Create a new object <code>SMH_short</code> that shows only <code>ID</code>, and the 7 subscales of <code>ToAS</code> (<code>APD:AMiscell</code>).
</p>
<p>
Step 2: use <code>gather()</code> according to the formula above so that the 7 subscales <code>APD:AMiscell</code> of <code>SMH_short</code> are gathered in one column named <code>Subscales</code> and their values in another column <code>Scores</code>. Store results in the <code>Global Environment</code> as <code>SMH_long</code>.
</p>
<p>
Step 3: <code>arrange()</code> the data <code>SMH_long</code> by the column <code>ID</code>. Store the results as <code>SMH_long</code>. You can either overwrite <code>SMH_long</code> from Step 2 or use a pipe (<code>%&gt;%</code>).
</p>
<p>
When you are done, <code>SMH_long</code> should look like this.
</p>
</div>
<pre><code>## # A tibble: 1,876 x 3
##       ID Subscales Scores
##    &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1     1 APD           23
##  2     1 AHome          9
##  3     1 APH           11
##  4     1 Afear          8
##  5     1 ACS           11
##  6     1 AGuilt         2
##  7     1 AMiscell      27
##  8     2 APD            8
##  9     2 AHome          7
## 10     2 APH            5
## # ... with 1,866 more rows</code></pre>
<div class="solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb221-1"></a>SMH_short &lt;-<span class="st"> </span><span class="kw">select</span>(data_SMH, ID, APD<span class="op">:</span>AMiscell)</span>
<span id="cb221-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb221-2"></a>SMH_long &lt;-<span class="st"> </span>SMH_short <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb221-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb221-3"></a><span class="st">  </span><span class="kw">gather</span>(Subscales, Scores, APD<span class="op">:</span>AMiscell) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb221-4"><a href="data-transformation-3-finetuned-data-manipulation.html#cb221-4"></a><span class="st">  </span><span class="kw">arrange</span>(ID)</span>
<span id="cb221-5"><a href="data-transformation-3-finetuned-data-manipulation.html#cb221-5"></a>SMH_long</span></code></pre></div>
<pre><code>## # A tibble: 1,876 x 3
##       ID Subscales Scores
##    &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1     1 APD           23
##  2     1 AHome          9
##  3     1 APH           11
##  4     1 Afear          8
##  5     1 ACS           11
##  6     1 AGuilt         2
##  7     1 AMiscell      27
##  8     2 APD            8
##  9     2 AHome          7
## 10     2 APH            5
## # ... with 1,866 more rows</code></pre>
<div class="solved">
<p>
A more detailed explanation:
</p>
<ul>
<li>
We needed a dataframe that we want to modify -&gt; <code>SMH_short</code>
</li>
<li>
We needed to come up with the name of a new column in which all the column headers of the 7 subscales will be stored -&gt; <code>Subscales</code>
</li>
<li>
We needed to come up with the name of a new column in which all the cell values of the 7 subscales will be stored -&gt; <code>Scores</code>
</li>
<li>
And finally, we needed to tell R which columns in the dataframe <code>SMH_short</code> we wanted to turn into long format (i.e. the columns of the 7 subscales) -&gt; <code>APD:AMiscell</code>
</li>
</ul>
<p>
<code>SMH_short</code> has 268 observations and 8 variables, whereas the rearranged <code>SMH_long</code> has 1876 observations and 3 columns - <code>ID</code> (which was there before) and the two new columns <code>Subscales</code> and <code>Scores</code> we created within <code>gather()</code>. After sorting it by <code>ID</code> we can see that each of the 268 participants have now 7 rows of observation - one for each subscale.
</p>
</div>
</div>
</div>
<div id="spread" class="section level3">
<h3><span class="header-section-number">5.2.2</span> spread()</h3>
<p>Now onto the reverse. <code>spread()</code> will spread the data from <code>long</code> into <code>wide format</code>. When you have observation that are scattered across multiple rows, you can use <code>spread()</code> to split rows up into separate variables. For example, <code>table2</code> has the variabes <code>cases</code> and <code>population</code> stored in one column <code>type</code>, however, they are separate variables rather than values of <code>type</code>. So best to get <code>cases</code> and <code>population</code> back into their own columns.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb223-1"></a>table2</span></code></pre></div>
<pre><code>## # A tibble: 12 x 4
##    country      year type            count
##    &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;           &lt;int&gt;
##  1 Afghanistan  1999 cases             745
##  2 Afghanistan  1999 population   19987071
##  3 Afghanistan  2000 cases            2666
##  4 Afghanistan  2000 population   20595360
##  5 Brazil       1999 cases           37737
##  6 Brazil       1999 population  172006362
##  7 Brazil       2000 cases           80488
##  8 Brazil       2000 population  174504898
##  9 China        1999 cases          212258
## 10 China        1999 population 1272915272
## 11 China        2000 cases          213766
## 12 China        2000 population 1280428583</code></pre>
<p>Take a look how <code>spread()</code> achieves that.</p>
<p><br></p>
<center>
<img src="images/spread.PNG" >
</center>
<p><br></p>
<p>Let’s apply the formula above to <code>table2</code>:</p>
<ul>
<li>We need a dataframe that we want to modify -&gt; <code>table2</code></li>
<li>We need to decide which of the columns in <code>table2</code> will become the new column headers -&gt; <code>type</code></li>
<li>We need to decide which of the columns in <code>table2</code> has all the data in it that will become the new cell values -&gt; <code>count</code></li>
</ul>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb225-1"></a><span class="kw">spread</span>(table2, <span class="dt">key =</span> type, <span class="dt">value =</span> count)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country      year  cases population
##   &lt;chr&gt;       &lt;int&gt;  &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan  1999    745   19987071
## 2 Afghanistan  2000   2666   20595360
## 3 Brazil       1999  37737  172006362
## 4 Brazil       2000  80488  174504898
## 5 China        1999 212258 1272915272
## 6 China        2000 213766 1280428583</code></pre>
<p>Voila, <code>cases</code> and <code>population</code> are in their own columns.</p>
<div class="task">
<p>
<strong>Your turn</strong>
</p>
<p>
Let’s pretend that the 7 subscales in <code>SMH_long</code> are actually 7 variables. Use <code>spread()</code> to achieve that. Store your results in the <code>Global Environment</code> as <code>SMH_wide</code>. When you are done, your results should look like this.
</p>
</div>
<pre><code>## # A tibble: 268 x 8
##       ID   ACS Afear AGuilt AHome AMiscell   APD   APH
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1     1    11     8      2     9       27    23    11
##  2     2     3     4      2     7       10     8     5
##  3     3     4     6      3     4       14    13     7
##  4     4     6     8      4    10       21    16    10
##  5     5     7     8      4    12       31    15     5
##  6     6     7     8      3     8       29    18    10
##  7     7     3     5      2     6       15    17    10
##  8     8    11    15      6    20       40    16    19
##  9     9    10    13      6    12       33    22    13
## 10    10     3    12      2     4       17     8     5
## # ... with 258 more rows</code></pre>
<div class="solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb228-1"></a>SMH_wide &lt;-<span class="st"> </span><span class="kw">spread</span>(SMH_long, Subscales, Scores)</span></code></pre></div>
<div class="solved">
<p>
A more detailed explanation
</p>
<ul>
<li>
We needed a dataframe that we want to modify -&gt; <code>SMH_long</code>
</li>
<li>
We needed to decide which of the columns in <code>SMH_long</code> would become the new column headers -&gt; <code>Subscales</code>
</li>
<li>
We needed to decide which of the columns in <code>SMH_long</code> had all the data in it that would become the new cell values -&gt; <code>Scores</code>
</li>
</ul>
</div>
<p>Now the 7 subscales are back in separate columns each.</p>
</div>
<p>Most of the time, data isn’t collected in a way that is useful for us (or R). It can happen that the data for the whole experiment is stored in a 2-column format. For example, some online platforms would give you a column in which all your dependent variables are stored, and another one that recorded the responses of the participants to that variable. That wouldn’t be a very useful format to analyse anything really.</p>
<center>
<img src="images/spread.PNG" >
</center>
<p>Let’s apply the formula above to our data and store results in the <code>Global Environment</code> as <code>SMH_wide</code>.</p>
<ul>
<li>We need a dataframe that we want to modify -&gt; <code>SMH_long</code></li>
<li>We need to decide which of the columns in <code>SMH_long</code> will become the new column headers -&gt; <code>Subscales</code></li>
<li>We need to decide which of the columns in <code>SMH_long</code> has all the data in it that will become the new cell values -&gt; <code>Scores</code></li>
</ul>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb229-1"></a>SMH_wide &lt;-<span class="st"> </span><span class="kw">spread</span>(SMH_long, Subscales, Scores)</span>
<span id="cb229-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb229-2"></a>SMH_wide</span></code></pre></div>
<pre><code>## # A tibble: 268 x 8
##       ID   ACS Afear AGuilt AHome AMiscell   APD   APH
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1     1    11     8      2     9       27    23    11
##  2     2     3     4      2     7       10     8     5
##  3     3     4     6      3     4       14    13     7
##  4     4     6     8      4    10       21    16    10
##  5     5     7     8      4    12       31    15     5
##  6     6     7     8      3     8       29    18    10
##  7     7     3     5      2     6       15    17    10
##  8     8    11    15      6    20       40    16    19
##  9     9    10    13      6    12       33    22    13
## 10    10     3    12      2     4       17     8     5
## # ... with 258 more rows</code></pre>
</div>
</div>
<div id="unite-and-separate" class="section level2">
<h2><span class="header-section-number">5.3</span> unite() and separate()</h2>
<p>Let’s start this part of by looking at a practical example in the build-in dataset <code>table1</code> to <code>table5</code>. They show the number of Tuberculosis cases documented by the World Health Organization in Afghanistan, Brazil, and China between 1999 and 2000. The data is part of the <code>tidyverse</code> package, so as long as we have <code>tidyverse</code> loaded into the library, there should not be an issue in accessing this dataset.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb231-1"></a>table1</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country      year  cases population
##   &lt;chr&gt;       &lt;int&gt;  &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan  1999    745   19987071
## 2 Afghanistan  2000   2666   20595360
## 3 Brazil       1999  37737  172006362
## 4 Brazil       2000  80488  174504898
## 5 China        1999 212258 1272915272
## 6 China        2000 213766 1280428583</code></pre>
<p><code>table1</code> has a very tidy structure. You can see the data contains values associated with four variables (<code>country</code>, <code>year</code>, <code>cases</code>, and <code>population</code>). <code>table5</code> however, looks a touch not right.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb233-1"></a>table5</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country     century year  rate             
## * &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;            
## 1 Afghanistan 19      99    745/19987071     
## 2 Afghanistan 20      00    2666/20595360    
## 3 Brazil      19      99    37737/172006362  
## 4 Brazil      20      00    80488/174504898  
## 5 China       19      99    212258/1272915272
## 6 China       20      00    213766/1280428583</code></pre>
<div class="task">
<p>
Take 2 min with the person next to you to discuss what is wrong with this tibble.
</p>
</div>
<div class="solution">
<button>
Solution
</button>
<div class="solved">
<ol style="list-style-type: decimal">
<li>
column <code>rate</code> holds the values for <code>cases</code> and <code>population</code> in one cell, separated by a <code>/</code>
</li>
<li>
the values in column <code>year</code> are split into <code>century</code> and <code>year</code>
</li>
</ol>
</div>
</div>
<p>This is where the functions <code>separate()</code> and <code>unite()</code> come in handy. We would use <code>separate()</code> to split the column <code>rate</code> back into two columns, and <code>unite()</code> (the inverse of separate) to combine <code>century</code> and <code>year</code> into a single column.</p>
<p>The function <code>separate()</code> is structured like this</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb235-1"></a><span class="kw">separate</span>(data, column_to_sep, <span class="dt">into =</span> <span class="kw">c</span>(new_column1, new_column2), <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<p>We would need</p>
<ul>
<li>the data in which the column to separate is located,</li>
<li>the actual colum we want to separate,</li>
<li>the into argument telling into how many columns we want to separate the old column and what we want to call these new columns, and</li>
<li>a separator argument.</li>
</ul>
<p>Let’s tackle the first problem, splitting <code>rate</code> back into two columns <code>cases</code> and <code>population</code>/</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb236-1"></a><span class="kw">separate</span>(table5, rate, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;cases&quot;</span>, <span class="st">&quot;population&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   country     century year  cases  population
##   &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;     
## 1 Afghanistan 19      99    745    19987071  
## 2 Afghanistan 20      00    2666   20595360  
## 3 Brazil      19      99    37737  172006362 
## 4 Brazil      20      00    80488  174504898 
## 5 China       19      99    212258 1272915272
## 6 China       20      00    213766 1280428583</code></pre>
<p>We have told R to separate the column <code>rate</code> (which is located in <code>table5</code>) into two new columns <code>cases</code> and <code>population</code>. The separator argument was set to a forward slash (<code>/</code>), and R will put all cell information before the <code>/</code> into <code>cases</code>, and everything after the <code>/</code> into <code>population</code>.</p>
<p>If for some reason, you wanted to keep the original column, you can set an additional argument <code>remove</code> to <code>FALSE</code>.</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb238-1"></a><span class="kw">separate</span>(table5, rate, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;cases&quot;</span>, <span class="st">&quot;population&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>, <span class="dt">remove =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   country     century year  rate              cases  population
##   &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;             &lt;chr&gt;  &lt;chr&gt;     
## 1 Afghanistan 19      99    745/19987071      745    19987071  
## 2 Afghanistan 20      00    2666/20595360     2666   20595360  
## 3 Brazil      19      99    37737/172006362   37737  172006362 
## 4 Brazil      20      00    80488/174504898   80488  174504898 
## 5 China       19      99    212258/1272915272 212258 1272915272
## 6 China       20      00    213766/1280428583 213766 1280428583</code></pre>
<p>What if you are just interested retaining part of the data in the cell, for example you want to keep the column <code>cases</code> but not <code>population</code>. The solution is to work with an <code>NA</code> argument. Defining the new columns as <code>cases</code> and <code>NA</code> will keep everything before the separator in the column <code>cases</code>, and drops everything after the separator.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb240-1"></a><span class="kw">separate</span>(table5, rate, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;cases&quot;</span>, <span class="ot">NA</span>), <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country     century year  cases 
##   &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt; 
## 1 Afghanistan 19      99    745   
## 2 Afghanistan 20      00    2666  
## 3 Brazil      19      99    37737 
## 4 Brazil      20      00    80488 
## 5 China       19      99    212258
## 6 China       20      00    213766</code></pre>
<div class="info">
<p>
By the way, the separator argument <code>sep =</code> can be anything, for example an
</p>
<ul>
<li>
underscore ("_"),
</li>
<li>
comma (“,”),
</li>
<li>
semi-colon (“;”),
</li>
<li>
colon (“:”),
</li>
<li>
forward-slash (“/”),
</li>
<li>
space (" ") or
</li>
<li>
nothing ("").
</li>
</ul>
<p>
It is also possible to separate by position. <code>sep = 2</code> would split the column between the second and third character/ number etc.
</p>
<p>
Technically, you would not need a separator argument in the case above, as <code>separate()</code> splits the data whenever it detects a non-alphanumeric character (i.e. a character that isn’t a number or letter). Saying that, the separator argument is needed when your column contains non-alphanumeric characters as part of your cell values.
</p>
<p>
But watch out! When the separator is a <code>full stop</code>, you would need to add a double backward slash in front of it (<code>sep = “\\.”</code>).
</p>
</div>
<p>Let’s try that the separation by position. We will keep 4 letters from each <code>country</code> name rather than the whole word, and drop the rest.</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb242-1"></a><span class="kw">separate</span>(table5, country, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;country&quot;</span>, <span class="ot">NA</span>), <span class="dt">sep =</span> <span class="dv">4</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country century year  rate             
##   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;            
## 1 Afgh    19      99    745/19987071     
## 2 Afgh    20      00    2666/20595360    
## 3 Braz    19      99    37737/172006362  
## 4 Braz    20      00    80488/174504898  
## 5 Chin    19      99    212258/1272915272
## 6 Chin    20      00    213766/1280428583</code></pre>
<p>Yay! Notice how <code>rate</code> is back to one column with both values in each row since we haven’t stored any output in the <code>Global Environment</code>.</p>
<p>There is only one thing left to do, and that is combining the columns <code>century</code> and <code>year</code> into a new column called <code>year</code>. Here, we can use the function <code>unite()</code> which is structured like</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb244-1"></a><span class="kw">unite</span>(data, new_column, col_to_unite1, col_to_unite2, <span class="dt">sep =</span> <span class="st">&quot;_&quot;</span>)</span></code></pre></div>
<p>We would need the data <code>table5</code>, a new column we want to create <code>year</code>, the two columns we would like to combine (<code>century</code> and <code>year</code>), and define the separator as “nothing” since the default is sep = "_".</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb245-1"></a><span class="kw">unite</span>(table5, year, century, year, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p>Right, let’s combine the two steps of tidying the <code>table5</code> data by creating a pipe <code>%&gt;%</code> and store the new object <code>tb_cases</code> in the <code>Global Environment</code>.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb246-1"></a>tb_cases &lt;-<span class="st"> </span>table5 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb246-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb246-2"></a><span class="st">  </span><span class="kw">separate</span>(rate, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;cases&quot;</span>, <span class="st">&quot;population&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb246-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb246-3"></a><span class="st">  </span><span class="kw">unite</span>(year, century, year, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb246-4"><a href="data-transformation-3-finetuned-data-manipulation.html#cb246-4"></a>tb_cases</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country     year  cases  population
##   &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;     
## 1 Afghanistan 1999  745    19987071  
## 2 Afghanistan 2000  2666   20595360  
## 3 Brazil      1999  37737  172006362 
## 4 Brazil      2000  80488  174504898 
## 5 China       1999  212258 1272915272
## 6 China       2000  213766 1280428583</code></pre>
<div class="question">
<p>
There is still a tiny bit off in the tibble above. Can you spot what it is? * Hint: Think about if you wanted to sum up all the TB cases occured in the 3 countries within the years 1999, and 2000.
</p>
</div>
<div class="solution">
<button>
Solution
</button>
<div class="solved">
<p>
All the columns are <code>character</code> columns. For any calculation however, the columns need to be <code>numerical</code>. The quickest solution would be to add another argument <code>convert</code> to <code>separate()</code> and set it to <code>TRUE</code>.
</p>
</div>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb248-1"></a>tb_cases &lt;-<span class="st"> </span>table5 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb248-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb248-2"></a><span class="st">  </span><span class="kw">separate</span>(rate, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;cases&quot;</span>, <span class="st">&quot;population&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>, <span class="dt">convert =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb248-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb248-3"></a><span class="st">  </span><span class="kw">unite</span>(year, century, year, <span class="dt">sep =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb248-4"><a href="data-transformation-3-finetuned-data-manipulation.html#cb248-4"></a>tb_cases</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country     year   cases population
##   &lt;chr&gt;       &lt;chr&gt;  &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan 1999     745   19987071
## 2 Afghanistan 2000    2666   20595360
## 3 Brazil      1999   37737  172006362
## 4 Brazil      2000   80488  174504898
## 5 China       1999  212258 1272915272
## 6 China       2000  213766 1280428583</code></pre>
<div class="question">
<p>
Unfortunately, <code>unite()</code> does not have a <code>convert</code> statement available. If you wanted to set column <code>year</code> as an <code>interger</code>, you would have to <code>mutate</code> the column. How would you do this?
</p>
</div>
<div class="solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb250-1"></a>tb_cases &lt;-<span class="st"> </span>tb_cases <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb250-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb250-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="kw">as.integer</span>(year))</span>
<span id="cb250-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb250-3"></a>tb_cases</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country      year  cases population
##   &lt;chr&gt;       &lt;int&gt;  &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan  1999    745   19987071
## 2 Afghanistan  2000   2666   20595360
## 3 Brazil       1999  37737  172006362
## 4 Brazil       2000  80488  174504898
## 5 China        1999 212258 1272915272
## 6 China        2000 213766 1280428583</code></pre>
</div>
</div>
<p>Special case. Let’s modify table5 a little bit by adding a new column with a value of 200 and unite that column with column <code>rate</code></p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb252-1"></a>table5_mod &lt;-<span class="st"> </span>table5 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb252-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb252-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">new =</span> <span class="dv">200</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb252-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb252-3"></a><span class="st">  </span><span class="kw">unite</span>(rate, rate, new, <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>)</span></code></pre></div>
<p>Now column <code>rate</code> has 3 sets of numbers, separated by two <code>/</code>. If we define we want to split the data into 2 columns, the first 2 sets of numbers are kept, and the third one is dropped with a warning.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb253-1"></a><span class="kw">separate</span>(table5_mod, rate, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;cases&quot;</span>, <span class="st">&quot;population&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Expected 2 pieces. Additional pieces discarded in 6 rows [1, 2, 3,
## 4, 5, 6].</code></pre>
<pre><code>## # A tibble: 6 x 5
##   country     century year  cases  population
##   &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;     
## 1 Afghanistan 19      99    745    19987071  
## 2 Afghanistan 20      00    2666   20595360  
## 3 Brazil      19      99    37737  172006362 
## 4 Brazil      20      00    80488  174504898 
## 5 China       19      99    212258 1272915272
## 6 China       20      00    213766 1280428583</code></pre>
<p>If we are separating the columns and wanted to keep all sets of numbers, one in each column, we would use an into argument that includes 3 new columns.</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb256-1"></a><span class="kw">separate</span>(table5_mod, rate, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;cases&quot;</span>, <span class="st">&quot;population&quot;</span>, <span class="st">&quot;200&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   country     century year  cases  population `200`
##   &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;
## 1 Afghanistan 19      99    745    19987071   200  
## 2 Afghanistan 20      00    2666   20595360   200  
## 3 Brazil      19      99    37737  172006362  200  
## 4 Brazil      20      00    80488  174504898  200  
## 5 China       19      99    212258 1272915272 200  
## 6 China       20      00    213766 1280428583 200</code></pre>
<p>However, what if we just wanted to split the data into 2 columns, after the first <code>/</code> AND keep all sets of numbers? We would have to include an <code>extra</code> argument, and set it to <code>"merge"</code>.</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb258-1"></a><span class="kw">separate</span>(table5_mod, rate, <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;cases&quot;</span>, <span class="st">&quot;population&quot;</span>), <span class="dt">sep =</span> <span class="st">&quot;/&quot;</span>, <span class="dt">extra =</span> <span class="st">&quot;merge&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   country     century year  cases  population    
##   &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;         
## 1 Afghanistan 19      99    745    19987071/200  
## 2 Afghanistan 20      00    2666   20595360/200  
## 3 Brazil      19      99    37737  172006362/200 
## 4 Brazil      20      00    80488  174504898/200 
## 5 China       19      99    212258 1272915272/200
## 6 China       20      00    213766 1280428583/200</code></pre>
</div>
<div id="rename" class="section level2">
<h2><span class="header-section-number">5.4</span> rename()</h2>
<p><code>rename()</code> is a very useful function if we wanted to change column names. All available column names are retained, so nothing is lost. It follows a very simple pattern of</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb260-1"></a><span class="kw">rename</span>(data, <span class="dt">new_column_name =</span> old_column_name)</span></code></pre></div>
<p>You can rename multiple column headers by including more arguments, separarting them with a comma. Let’s take a look at a simple example in <code>table1</code>.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb261-1"></a>table1</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   country      year  cases population
##   &lt;chr&gt;       &lt;int&gt;  &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan  1999    745   19987071
## 2 Afghanistan  2000   2666   20595360
## 3 Brazil       1999  37737  172006362
## 4 Brazil       2000  80488  174504898
## 5 China        1999 212258 1272915272
## 6 China        2000 213766 1280428583</code></pre>
<p>If we wanted to change the column headers of <code>country</code> to <code>Country</code> and <code>population</code> to <code>Population</code>, we would code</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb263-1"></a><span class="kw">rename</span>(table1, <span class="dt">Country =</span> country,</span>
<span id="cb263-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb263-2"></a>       <span class="dt">Population =</span> population)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   Country      year  cases Population
##   &lt;chr&gt;       &lt;int&gt;  &lt;int&gt;      &lt;int&gt;
## 1 Afghanistan  1999    745   19987071
## 2 Afghanistan  2000   2666   20595360
## 3 Brazil       1999  37737  172006362
## 4 Brazil       2000  80488  174504898
## 5 China        1999 212258 1272915272
## 6 China        2000 213766 1280428583</code></pre>
<p>If you want to select a few columns and rename them in the process, you could use <code>select()</code>. The structure is the same as with <code>rename()</code>, the only difference is that the new data only retains the columns mentioned explicitly within <code>select()</code>.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb265-1"></a><span class="kw">select</span>(data, <span class="dt">new_column_name =</span> old_column_name)</span></code></pre></div>
<p>Modifying the <code>rename()</code> example from above would lead to selecting the columns <code>country</code> and <code>population</code> from <code>table1</code> and renaming them as <code>Country</code> and <code>Population</code> at the same time.</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb266-1"></a><span class="kw">select</span>(table1, <span class="dt">Country =</span> country,</span>
<span id="cb266-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb266-2"></a>       <span class="dt">Population =</span> population)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   Country     Population
##   &lt;chr&gt;            &lt;int&gt;
## 1 Afghanistan   19987071
## 2 Afghanistan   20595360
## 3 Brazil       172006362
## 4 Brazil       174504898
## 5 China       1272915272
## 6 China       1280428583</code></pre>
</div>
<div id="recode" class="section level2">
<h2><span class="header-section-number">5.5</span> recode()</h2>
<p>works with mutate</p>
</div>
<div id="ifelse-and-case_when" class="section level2">
<h2><span class="header-section-number">5.6</span> ifelse and case_when</h2>
<p>in combination with mutate</p>
<p>We can recode the Age groups…</p>
<p>use %in% so that they can do the homework task - we did not explain that in filter</p>
</div>
<div id="distinct" class="section level2">
<h2><span class="header-section-number">5.7</span> distinct</h2>
<p>The <code>distinct()</code> function is used to remove duplicate rows in your dataframe. If we are using <code>distinct()</code> without specifying any arguments, R checks the whole row and excludes any row that is exactly repeated.</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb268-1"></a>data_SMH_no_dup &lt;-<span class="st"> </span>data_SMH <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb268-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb268-2"></a><span class="st">  </span><span class="kw">distinct</span>()</span></code></pre></div>
<p>We can see that all rows are still there. This is not surprising, given every participant has a unique ID number. We could exclude the <code>ID</code> column to check how many full rows are exactly identical.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb269-1"></a>data_SMH_no_dup &lt;-<span class="st"> </span>data_SMH <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb269-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb269-2"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>ID) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb269-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb269-3"></a><span class="st">  </span><span class="kw">distinct</span>()</span></code></pre></div>
<p>We can see here that 5 rows were excluded as <code>data_SMH_no_dup</code> has 263 observations compared to 268 in <code>data_SMH</code>.</p>
<p><code>distinct()</code> does take arguments as well, namely the variable columns you are trying to determine uniqueness for. Say we we wanted to investigate how many regions are included in <code>data_SMH</code>.</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb270-1"></a>regions &lt;-<span class="st"> </span>data_SMH <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb270-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb270-2"></a><span class="st">  </span><span class="kw">distinct</span>(Region)</span>
<span id="cb270-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb270-3"></a></span>
<span id="cb270-4"><a href="data-transformation-3-finetuned-data-manipulation.html#cb270-4"></a>regions</span></code></pre></div>
<pre><code>## # A tibble: 5 x 1
##   Region
##   &lt;chr&gt; 
## 1 SEA   
## 2 EA    
## 3 SA    
## 4 Others
## 5 JAP</code></pre>
<p>We can see that there are 5 distinct regions. But what happened to the output? Now we have an overview that people were from 5 distinct regions, but we have lost all the other data in the dataframe. One quick solution would be to use the argument <code>.keep_all</code> and set that to <code>TRUE</code> (the default here is <code>FALSE</code>).</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb272-1"></a>regions &lt;-<span class="st"> </span>data_SMH <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb272-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb272-2"></a><span class="st">  </span><span class="kw">distinct</span>(Region, <span class="dt">.keep_all =</span> <span class="ot">TRUE</span>)</span>
<span id="cb272-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb272-3"></a></span>
<span id="cb272-4"><a href="data-transformation-3-finetuned-data-manipulation.html#cb272-4"></a>regions</span></code></pre></div>
<pre><code>## # A tibble: 5 x 19
##      ID inter_dom Region Gender Academic   Age Stay_Cate Japanese_cate
##   &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;        
## 1     1 Inter     SEA    Male   Grad        24 Long      Average      
## 2     4 Inter     EA     Female Grad        29 Short     Low          
## 3     7 Inter     SA     Male   Grad        23 Short     Average      
## 4    10 Inter     Others Male   Grad        31 Medium    Low          
## 5    39 Inter     JAP    Female Under       21 Long      High         
## # ... with 11 more variables: English_cate &lt;chr&gt;, ToDep &lt;dbl&gt;, ToSC &lt;dbl&gt;,
## #   APD &lt;dbl&gt;, AHome &lt;dbl&gt;, APH &lt;dbl&gt;, Afear &lt;dbl&gt;, ACS &lt;dbl&gt;,
## #   AGuilt &lt;dbl&gt;, AMiscell &lt;dbl&gt;, ToAS &lt;dbl&gt;</code></pre>
<p>In the new <code>regions</code> dataframe, we still have 5 rows of observations but we kept all 19 columns. If there are multiple rows with the same input (in this case 268 people came from 5 different regions), <code>distinct()</code> only preserves the first row a new value occurs.</p>
<p>The <code>distinct()</code> function also allows you to eliminate duplicate rows with multiple variables in the dataframe. So if we wanted to see how many different regions participants were from, but also whether they are male or female, we would type…</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb274-1"></a>RegGen &lt;-<span class="st"> </span>data_SMH <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb274-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb274-2"></a><span class="st">  </span><span class="kw">distinct</span>(Region, Gender)</span>
<span id="cb274-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb274-3"></a></span>
<span id="cb274-4"><a href="data-transformation-3-finetuned-data-manipulation.html#cb274-4"></a>RegGen</span></code></pre></div>
<pre><code>## # A tibble: 10 x 2
##    Region Gender
##    &lt;chr&gt;  &lt;chr&gt; 
##  1 SEA    Male  
##  2 EA     Female
##  3 SA     Male  
##  4 SEA    Female
##  5 Others Male  
##  6 Others Female
##  7 EA     Male  
##  8 SA     Female
##  9 JAP    Female
## 10 JAP    Male</code></pre>
<p><code>RegGen</code> has 10 observations, so that means, we have at least 1 male and 1 female participant from each of the 5 regions.</p>
<div class="question">
<p>
You can see they are not sorted by either of the column. Why is that?
</p>
</div>
<div class="solution">
<button>
Solution
</button>
<div class="solved">
<p>
The values are sorted by occurence. R goes throgh the tibble row by row to determine whether the values are distinct from the ones in the row before. So if you look at your original dataframe <code>data_SMH</code>, you can see the first row is a male participant from SEA. But the participants in rows 2 and 3 are also males from SEA. The next unique value would be detected in row 4, then in row 7 (as row 5 is the same as 4, and row 6 is a repetition of row 1), then in row 8, …
</p>
</div>
</div>
<div class="info">
<p>
You can add as many variables as you like, however they need to be separated by a comma. <code>distinct()</code> does not take any “shortcuts” such as <code>inter_dom:ToAS</code>. Don’t believe it? Try it out in your <code>Console</code>.
</p>
</div>
</div>
<div id="additional-information-1" class="section level2">
<h2><span class="header-section-number">5.8</span> Additional information</h2>
<p>More information on stuff we covered today and beyond can be found here:</p>
<ul>
<li><a href="https://r4ds.had.co.nz" class="uri">https://r4ds.had.co.nz</a> “R 4 Data Science” by Garrett Grolemund and Hadley Wickham is the official guidebook for R</li>
<li><a href="https://suzan.rbind.io/categories/tutorial/" class="uri">https://suzan.rbind.io/categories/tutorial/</a> She has some pretty cool tutorials on data wrangling</li>
</ul>
</div>
<div id="bonus-mutate-rownames-from-the-mtcars" class="section level2">
<h2><span class="header-section-number">5.9</span> Bonus: mutate rownames from the mtcars</h2>
<p>Remember, in lecture 2 when we were talking about the mtcars dataset and how the car types were not in listed as a separate column but rather rownames? Let’s just read in the data and have another quick look to jug our memories…</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb276-1"></a>df_mtcars &lt;-<span class="st"> </span>mtcars</span>
<span id="cb276-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb276-2"></a></span>
<span id="cb276-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb276-3"></a><span class="kw">head</span>(df_mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
<p>You can see much better what I’m talking about when you view your <code>df_mtcars</code>.</p>
<p>Now, that we have learnt about the <code>mutate()</code> function, we can attempt to get all of these rownames into a new column. All we have to do is combining a function called <code>rownames()</code> with <code>mutate()</code>. We also could use some more of these handy pipes <code>%&gt;%</code> you learnt about last week.</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb278-1"></a>df_mtcars &lt;-<span class="st"> </span>mtcars <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb278-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb278-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Car_type =</span> <span class="kw">rownames</span>(mtcars))</span></code></pre></div>
<p>In this example, we have taken the dataset <code>mtcars</code>, then added a new column to it with <code>mutate()</code> in which we wanted the new column header to be named <code>Car_type</code>. The column <code>Car_type</code> should then hold all the values that were previously listed as the rownames in the original <code>mtcars</code> data.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb279-1"></a><span class="kw">head</span>(df_mtcars)</span></code></pre></div>
<pre><code>##    mpg cyl disp  hp drat    wt  qsec vs am gear carb          Car_type
## 1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4         Mazda RX4
## 2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4     Mazda RX4 Wag
## 3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1        Datsun 710
## 4 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1    Hornet 4 Drive
## 5 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2 Hornet Sportabout
## 6 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1           Valiant</code></pre>
<div class="question">
<p>
We can now look at the data <code>df_mtcars</code>, and see that the new column was added at the end of the dataset. What would we have to do to make <code>Car_type</code> the first column in the dataframe?
</p>
</div>
<div class="solution">
<button>
Answer
</button>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="data-transformation-3-finetuned-data-manipulation.html#cb281-1"></a><span class="co"># We could use the fuction select()</span></span>
<span id="cb281-2"><a href="data-transformation-3-finetuned-data-manipulation.html#cb281-2"></a>df_mtcars &lt;-<span class="st"> </span>mtcars <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb281-3"><a href="data-transformation-3-finetuned-data-manipulation.html#cb281-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Car_type =</span> <span class="kw">rownames</span>(mtcars)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb281-4"><a href="data-transformation-3-finetuned-data-manipulation.html#cb281-4"></a><span class="st">  </span><span class="kw">select</span>(Car_type, mpg<span class="op">:</span>carb)</span>
<span id="cb281-5"><a href="data-transformation-3-finetuned-data-manipulation.html#cb281-5"></a></span>
<span id="cb281-6"><a href="data-transformation-3-finetuned-data-manipulation.html#cb281-6"></a><span class="kw">head</span>(df_mtcars)</span></code></pre></div>
<pre><code>##            Car_type  mpg cyl disp  hp drat    wt  qsec vs am gear carb
## 1         Mazda RX4 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## 2     Mazda RX4 Wag 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## 3        Datsun 710 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## 4    Hornet 4 Drive 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## 5 Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## 6           Valiant 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
</div>
</div>
<div id="formative-homework-1" class="section level2">
<h2><span class="header-section-number">5.10</span> Formative Homework</h2>

</div>
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="data-transformation-2-two-table-verbs.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="recap-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
